### Dealing with Duplicate values Missing Data

In [1]:
import pandas as pd
import numpy as np

### Duplicate Values

In [2]:
cdata=pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [3]:
cdata.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [4]:
cdata[cdata.duplicated()]

    EEID   Name gender   salary
6  EMP02  rohit      M  25000.0

In [5]:
cdata['EEID'].duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
Name: EEID, dtype: bool

In [6]:
cdata[cdata['EEID'].duplicated()]

    EEID    Name gender   salary
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [7]:
cdata.drop_duplicates()

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN

In [8]:
cdata['EEID'].drop_duplicates()

0    EMP01
1    EMP02
2    EMP03
4    EMP05
5    EMP06
Name: EEID, dtype: object

In [9]:
#check null

cdata.isnull()
edata=pd.read_csv("subdata_pandas/employee.csv")
edata

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

In [ ]:
edata.isnull().sum()

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
469,False,False,False,False,False,False,False,False,False,False
470,False,False,False,False,False,False,False,False,False,False
471,False,False,False,False,False,False,False,False,False,False
472,False,False,False,False,False,False,False,False,False,False
473,False,False,False,False,False,False,False,False,False,False

In [27]:
edata['id'].isnull().sum()

np.int64(0)

In [39]:
#eliminate the null rows
cdata.dropna()

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [67]:
cdata.fillna(0)

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      0  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05         0      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0

In [57]:
#Replace nan with any value
cdata.replace(np.nan,"insuffient")

    EEID        Name      gender   salary
0  EMP01      ayushi           F  30000.0
1  EMP02       rohit           M  25000.0
2  EMP03    pranjali  insuffient  27000.0
3  EMP01      ayushi           F  20000.0
4  EMP05  insuffient           M  25000.0
5  EMP06       rohit           M  30000.0
6  EMP02       rohit           M  25000.0

In [59]:
#Replace nan with 3000 in salary
cdata['salary']=cdata['salary'].replace(np.nan,3000)
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0

In [ ]:
cdata['salary']=cdata['salary'].replace(0,np.nan).inplace
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [88]:
cdata['salary'].fillna(cdata['salary'].mean())
cdata['salary'].bfill()

0    25000.0
1    25000.0
2    27000.0
3    20000.0
4    25000.0
5    25000.0
6    25000.0
Name: salary, dtype: float64